obj-$(CONFIG_DISP_PM_DOMAIN_SHARKL3)	+= disp_pm_domain_sharkl3.o
#mm power
obj-$(CONFIG_SPRD_MM_PW_DOMAIN_R6P0) += mmsys_pw_domain_r6p0.o
obj-$(CONFIG_SPRD_CAM_PW_DOMAIN_R5P0) += camsys_pw_domain_r5p0.o
