/*
 * Copyright (C) 2017-2018 Spreadtrum Communications Inc.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _DCAM_REG_H_
#define _DCAM_REG_H_

#include <linux/bitops.h>

extern unsigned long s_dcam_regbase[];
extern unsigned long s_dcam_aximbase;
extern unsigned long s_dcam_mmubase;

#define DCAM_BASE(idx)                 (s_dcam_regbase[idx])


#define    DCAM_IP_REVISION                     (0x0000UL)
#define    DCAM_CONTROL                           (0x0004UL)
#define    DCAM_APB_SRAM_CTRL              (0x0008UL)
#define    DCAM_SPARE_CTRL                      (0x000CUL)
#define    DCAM_MIPI_CAP_CFG                  (0x0010UL)
#define    DCAM_MIPI_CAP_START              (0x0014UL)
#define    DCAM_MIPI_CAP_END                  (0x0018UL)
#define    DCAM_IMAGE_CONTROL               (0x001CUL)
#define    DCAM_MIPI_REDUNDANT             (0x0020UL)
#define    DCAM_CAP_FRM_CLR                   (0x0024UL)
#define    DCAM_CAP_RAW_SIZE                 (0x0028UL)
#define    DCAM_INIT_MASK                        (0x0030UL)
#define    DCAM_INT_EN                               (0x0034UL)
#define    DCAM_INT_CLR                             (0x0038UL)
#define    DCAM_INT_RAW                            (0x003CUL)
#define    DCAM_3A_INT_MASK                   (0x0040UL)
#define    DCAM_3A_INT_EN                        (0x0044UL)
#define    DCAM_3A_INT_CLR                      (0x0048UL)
#define    DCAM_3A_INT_RAW                     (0x004CUL)
#define    DCAM_PATH_OVF                          (0x0050UL)
#define    DCAM_PATH_BUSY                        (0x0054UL)
#define    DCAM_PATH_STOP                        (0x0058UL)
#define    DCAM_PATH_ENDIAN                    (0x005CUL)
#define    DCAM_FBC_PAYLOAD_WADDR     (0x0060UL)
#define    DCAM_FBC_MID_WADDR              (0x0064UL)
#define    DCAM_FULL_BASE_WADDR          (0x0068UL)
#define    DCAM_BIN_BASE_WADDR0          (0x0070UL)
#define    DCAM_BIN_BASE_WADDR1          (0x0074UL)
#define    DCAM_BIN_BASE_WADDR2          (0x0078UL)
#define    DCAM_BIN_BASE_WADDR3          (0x007CUL)
#define    DCAM_PDAF_BASE_WADDR         (0x0080UL)
#define    DCAM_VCH2_BASE_WADDR         (0x0084UL)
#define    DCAM_VCH3_BASE_WADDR         (0x0088UL)
#define    DCAM_PPE_RIGHT_WADDR          (0x008CUL)
#define    DCAM_LENS_BASE_RADDR          (0x0090UL)
#define    DCAM_LSCM_BASE_WADDR         (0x0094UL)
#define    DCAM_AEM_BASE_WADDR           (0x00A0UL)
#define    DCAM_AEM_BASE_WADDR1         (0x00A4UL)
#define    DCAM_AEM_BASE_WADDR2         (0x00A8UL)
#define    DCAM_AEM_BASE_WADDR3         (0x00ACUL)
#define    DCAM_HIST_BASE_WADDR          (0x00C0UL)
#define    DCAM_HIST_BASE_WADDR1        (0x00C4UL)
#define    DCAM_HIST_BASE_WADDR2        (0x00C8UL)
#define    DCAM_HIST_BASE_WADDR3        (0x00CCUL)
#define    ISP_AFL_GLB_WADDR                    (0x00D0UL)
#define    ISP_AFL_REGION_WADDR             (0x00D4UL)
#define    ISP_BPC_MAP_ADDR                      (0x00D8UL)
#define    ISP_BPC_OUT_ADDR                       (0x00DCUL)
#define    ISP_AFM_BASE_WADDR                 (0x00E0UL)
#define    ISP_NR3_WADDR                            (0x00E4UL)
#define    DCAM_FBC_CTRL                           (0x00F0UL)
#define    DCAM_FBC_CTRL0                         (0x00F4UL)
#define    DCAM_FBC_CTRL1                         (0x00F8UL)
#define    DCAM_FULL_CFG                           (0x0100UL)
#define    DCAM_FULL_CROP_START           (0x0104UL)
#define    DCAM_FULL_CROP_SIZE              (0x0108UL)
#define    DCAM_FULL_PATH_STATUS         (0x010CUL)
#define    DCAM_CAM_BIN_CFG                   (0x0120UL)
#define    DCAM_CAM_BIN_CROP_START   (0x0124UL)
#define    DCAM_CAM_BIN_CROP_SIZE      (0x0128UL)
#define    DCAM_RDS_DES_SIZE                 (0x012CUL)
#define    DCAM_RDS_SLICE_CTRL0           (0x0130UL)
#define    DCAM_RDS_SLICE_CTRL1           (0x0134UL)
#define    DCAM_RDS_SLICE_CTRL2           (0x0138UL)
#define    DCAM_RDS_SLICE_CTRL3           (0x013CUL)
#define    DCAM_BIN_PATH_STATUS           (0x0140UL)
#define    DCAM_VCH2_CONTROL                   (0x0160UL)
#define    DCAM_VCH2_PATH_STATUS           (0x0164UL)
#define    DCAM_VCH3_CONTROL                   (0x0170UL)
#define    DCAM_VCH3_PATH_STATUS           (0x0174UL)
#define    DCAM_BAYER_INFO_CFG              (0x0180UL)
#define    DCAM_BLC_PARA_R_B                  (0x0184UL)
#define    DCAM_BLC_PARA_G                      (0x0188UL)
#define    ISP_RGBG_RB                                   (0x01A0UL)
#define    ISP_RGBG_G                                     (0x01A4UL)
#define    ISP_RGBG_YRANDOM_PARAMETER0           (0x01A8UL)
#define    ISP_RGBG_YRANDOM_PARAMETER1           (0x01ACUL)
#define    ISP_RGBG_YRANDOM_PARAMETER2           (0x01B0UL)
#define    ISP_RGBG_YUV_YRANDOM_STATUS0          (0x01B4UL)
#define    ISP_RGBG_YUV_YRANDOM_STATUS1          (0x01B8UL)
#define    ISP_RGBG_YUV_YRANDOM_STATUS2          (0x01BCUL)
#define    DCAM_PDAF_CONTROL                     (0x0200UL)
#define    DCAM_PPE_FRM_CTRL0                    (0x0204UL)
#define    DCAM_PPE_FRM_CTRL1                    (0x0208UL)
#define    DCAM_PDAF_PATH_STATUS             (0x0210UL)
#define    ISP_PPI_PARAM                                  (0x0214UL)
#define    ISP_PPI_BLOCK_COL                          (0x0218UL)
#define    ISP_PPI_BLOCK_ROW                         (0x021CUL)
#define    ISP_PPI_GLB_START                           (0x0220UL)
#define    ISP_PPI_AF_WIN_START                    (0x0230UL)
#define    ISP_PPI_AF_WIN_END                  (0x0234UL)
#define    ISP_PPI_PATTERN01                     (0x0238UL)
#define    ISP_PPI_PATTERN02                     (0x023CUL)
#define    ISP_PPI_PATTERN03                     (0x0240UL)
#define    ISP_PPI_PATTERN04                     (0x0244UL)
#define    ISP_PPI_PATTERN05                     (0x0248UL)
#define    ISP_PPI_PATTERN06                     (0x024CUL)
#define    ISP_PPI_PATTERN07                     (0x0250UL)
#define    ISP_PPI_PATTERN08                     (0x0254UL)
#define    ISP_PPI_PATTERN09                     (0x0258UL)
#define    ISP_PPI_PATTERN10                     (0x025CUL)
#define    ISP_PPI_PATTERN11                     (0x0260UL)
#define    ISP_PPI_PATTERN12                     (0x0264UL)
#define    ISP_PPI_PATTERN13                     (0x0268UL)
#define    ISP_PPI_PATTERN14                     (0x026CUL)
#define    ISP_PPI_PATTERN15                     (0x0270UL)
#define    ISP_PPI_PATTERN16                     (0x0274UL)
#define    ISP_PPI_PATTERN17                     (0x0278UL)
#define    ISP_PPI_PATTERN18                     (0x027CUL)
#define    ISP_PPI_PATTERN19                     (0x0280UL)
#define    ISP_PPI_PATTERN20                     (0x0284UL)
#define    ISP_PPI_PATTERN21                     (0x0288UL)
#define    ISP_PPI_PATTERN22                     (0x028CUL)
#define    ISP_PPI_PATTERN23                     (0x0290UL)
#define    ISP_PPI_PATTERN24                     (0x0294UL)
#define    ISP_PPI_PATTERN25                     (0x0298UL)
#define    ISP_PPI_PATTERN26                     (0x029CUL)
#define    ISP_PPI_PATTERN27                     (0x02A0UL)
#define    ISP_PPI_PATTERN28                     (0x02A4UL)
#define    ISP_PPI_PATTERN29                     (0x02A8UL)
#define    ISP_PPI_PATTERN30                     (0x02ACUL)
#define    ISP_PPI_PATTERN31                     (0x02B0UL)
#define    ISP_PPI_PATTERN32                     (0x02B4UL)
#define    DCAM_LSCM_FRM_CTRL0           (0x02C0UL)
#define    DCAM_LSCM_FRM_CTRL1           (0x02C4UL)
#define    DCAM_LSCM_OFFSET                  (0x02C8UL)
#define    DCAM_LSCM_BLK_NUM              (0x02CCUL)
#define    DCAM_LSCM_BLK_SIZE              (0x02D0UL)
#define    DCAM_LENS_GRID_NUMBER             (0x02E0UL)
#define    DCAM_LENS_GRID_SIZE                   (0x02E4UL)
#define    DCAM_LENS_LOAD_ENABLE             (0x02E8UL)
#define    DCAM_LENS_LOAD_CLR                    (0x02ECUL)
#define    DCAM_LENS_SLICE_CTRL0               (0x02F0UL)
#define    DCAM_LENS_SLICE_CTRL1               (0x02F4UL)
#define    DCAM_LENS_STATUS                         (0x02F8UL)
#define    DCAM_AEM_FRM_CTRL0                   (0x0300UL)
#define    DCAM_AEM_FRM_CTRL1                   (0x0304UL)
#define    DCAM_AEM_OFFSET                          (0x0308UL)
#define    DCAM_AEM_BLK_NUM                       (0x030CUL)
#define    DCAM_AEM_BLK_SIZE                       (0x0310UL)
#define    DCAM_AEM_RED_THR                        (0x0314UL)
#define    DCAM_AEM_BLUE_THR                      (0x0318UL)
#define    DCAM_AEM_GREEN_THR                   (0x031CUL)
#define    DCAM_AEM_STATUS                          (0x0320UL)
#define    DCAM_HIST_FRM_CTRL0                  (0x0340UL)
#define    DCAM_HIST_FRM_CTRL1                  (0x0344UL)
#define    DCAM_BAYER_HIST_START              (0x0348UL)
#define    DCAM_BAYER_HIST_END                  (0x034CUL)
#define    DCAM_HIST_STATUS                         (0x0350UL)
#define    ISP_AFL_FRM_CTRL0                     (0x0360UL)
#define    ISP_AFL_FRM_CTRL1                     (0x0364UL)
#define    ISP_AFL_PARAM0                        (0x0368UL)
#define    ISP_AFL_PARAM1                        (0x036CUL)
#define    ISP_AFL_PARAM2                        (0x0370UL)
#define    ISP_AFL_COL_POS                       (0x0374UL)
#define    ISP_AFL_REGION0                       (0x0378UL)
#define    ISP_AFL_REGION1                       (0x037CUL)
#define    ISP_AFL_REGION2                       (0x0380UL)
#define    ISP_AFL_SUM1                          (0x0384UL)
#define    ISP_AFL_SUM2                          (0x0388UL)
#define    ISP_AFL_STATUS0                       (0x038CUL)
#define    ISP_AFL_STATUS1                       (0x0390UL)
#define    ISP_AFL_STATUS2                       (0x0394UL)
#define    ISP_AFL_SLICE1                       (0x0398UL)
#define    ISP_AFL_SLICE2                       (0x039CUL)
#define    ISP_AFL_SLICE3                       (0x03A0UL)
#define    ISP_AFL_SLICE4                       (0x03A4UL)
#define    DCAM_CROP0_START             (0x03C0UL)
#define    DCAM_CROP0_SIZE                (0x03C4UL)
#define    ISP_AWBC_GAIN0                        (0x03D0UL)
#define    ISP_AWBC_GAIN1                        (0x03D4UL)
#define    ISP_AWBC_THRD0                         (0x03D8UL)
#define    ISP_AWBC_THRD1                         (0x03DCUL)
#define    ISP_AWBC_OFFSET0                      (0x03E0UL)
#define    ISP_AWBC_OFFSET1                      (0x03E4UL)
#define    ISP_AWBC_STATUS                        (0x03E8UL)
#define    ISP_BPC_PARAM                            (0x0400UL)
#define    ISP_BPC_MAP_CTRL                      (0x0404UL)
#define    ISP_BPC_BAD_PIXEL_TH0                 (0x0408UL)
#define    ISP_BPC_BAD_PIXEL_TH1                 (0x040CUL)
#define    ISP_BPC_BAD_PIXEL_TH2                 (0x0410UL)
#define    ISP_BPC_BAD_PIXEL_TH3                 (0x0414UL)
#define    ISP_BPC_FLAT_TH                           (0x0418UL)
#define    ISP_BPC_EDGE_RATIO                    (0x041CUL)
#define    ISP_BPC_BAD_PIXEL_PARAM        (0x0420UL)
#define    ISP_BPC_BAD_PIXEL_COEFF          (0x0424UL)
#define    ISP_BPC_LUTWORD0                      (0x0428UL)
#define    ISP_BPC_LUTWORD1                      (0x042CUL)
#define    ISP_BPC_LUTWORD2                      (0x0430UL)
#define    ISP_BPC_LUTWORD3                      (0x0434UL)
#define    ISP_BPC_LUTWORD4                      (0x0438UL)
#define    ISP_BPC_LUTWORD5                      (0x043CUL)
#define    ISP_BPC_LUTWORD6                      (0x0440UL)
#define    ISP_BPC_LUTWORD7                      (0x0444UL)
#define    ISP_BPC_PPI_RANG                    (0x0448UL)
#define    ISP_BPC_PPI_RANG1                   (0x044CUL)
#define    ISP_BPC_PPI_GLB_START           (0x0450UL)
#define    ISP_BPC_SLICE_ROI_S                (0x0454UL)
#define    ISP_BPC_SLICE_ROI_R                (0x0458UL)
#define    ISP_BPC_LAST_ADDR                     (0x045CUL)
#define    ISP_BPC_STATUS0                       (0x0460UL)
#define    ISP_BPC_STATUS1                       (0x0464UL)
#define    ISP_AFM_FRM_CTRL                      (0x0480UL)
#define    ISP_AFM_FRM_CTRL1                     (0x0484UL)
#define    ISP_AFM_PARAMETERS                    (0x0488UL)
#define    ISP_AFM_ENHANCE_CTRL                  (0x048CUL)
#define    ISP_AFM_CROP_START                    (0x0490UL)
#define    ISP_AFM_CROP_SIZE                     (0x0494UL)
#define    ISP_AFM_WIN_RANGE0S                   (0x0498UL)
#define    ISP_AFM_WIN_RANGE0E                   (0x049CUL)
#define    ISP_AFM_WIN_RANGE1S                   (0x04A0UL)
#define    ISP_AFM_IIR_FILTER0                   (0x04A4UL)
#define    ISP_AFM_IIR_FILTER1                   (0x04A8UL)
#define    ISP_AFM_IIR_FILTER2                   (0x04ACUL)
#define    ISP_AFM_IIR_FILTER3                   (0x04B0UL)
#define    ISP_AFM_IIR_FILTER4                   (0x04B4UL)
#define    ISP_AFM_IIR_FILTER5                   (0x04B8UL)
#define    ISP_AFM_ENHANCE_FV0_THD               (0x04BCUL)
#define    ISP_AFM_ENHANCE_FV1_THD               (0x04C0UL)
#define    ISP_AFM_ENHANCE_FV1_COEFF00           (0x04C4UL)
#define    ISP_AFM_ENHANCE_FV1_COEFF01           (0x04C8UL)
#define    ISP_AFM_ENHANCE_FV1_COEFF10           (0x04CCUL)
#define    ISP_AFM_ENHANCE_FV1_COEFF11           (0x04D0UL)
#define    ISP_AFM_ENHANCE_FV1_COEFF20           (0x04D4UL)
#define    ISP_AFM_ENHANCE_FV1_COEFF21           (0x04D8UL)
#define    ISP_AFM_ENHANCE_FV1_COEFF30           (0x04DCUL)
#define    ISP_AFM_ENHANCE_FV1_COEFF31           (0x04E0UL)
#define    ISP_AFM_TILE_CNT_OUT                  (0x04E4UL)
#define    ISP_AFM_CNT_OUT                       (0x04E8UL)
#define    ISP_AFM_STATUS0                       (0x04ECUL)
#define    ISP_AFM_STATUS1                       (0x04F0UL)
#define    DCAM_NR3_FAST_ME_PARAM                     (0x0500UL)
#define    DCAM_NR3_FAST_ME_ROI_PARAM0                (0x0504UL)
#define    DCAM_NR3_FAST_ME_ROI_PARAM1                (0x0508UL)
#define    DCAM_NR3_FAST_ME_OUT0                      (0x050CUL)
#define    DCAM_NR3_FAST_ME_OUT1                      (0x0510UL)
#define    DCAM_NR3_FAST_ME_STATUS                    (0x0514UL)
#define    DCAM_GTM_GLB_CTRL                             (0x0520UL)
#define    DCAM_GTM_HIST_CTRL0                          (0x0524UL)
#define    DCAM_GTM_HIST_CTRL1                          (0x0528UL)
#define    DCAM_GTM_HIST_YMIN                          (0x052CUL)
#define    DCAM_GTM_HIST_CTRL2                          (0x0530UL)
#define    DCAM_GTM_HIST_CTRL3                          (0x0534UL)
#define    DCAM_GTM_HIST_CTRL4                          (0x0538UL)
#define    DCAM_GTM_HIST_CTRL5                          (0x053CUL)
#define    DCAM_GTM_HIST_CTRL6                          (0x0540UL)
#define    DCAM_GTM_HIST_CTRL7                          (0x0544UL)
#define    DCAM_GTM_LOG_DIFF                              (0x0548UL)
#define    DCAM_GTM_TM_YMIN_SMOOTH           (0x054CUL)
#define    DCAM_GTM_TM_LUMAFILTER0               (0x0550UL)
#define    DCAM_GTM_TM_LUMAFILTER1               (0x0554UL)
#define    DCAM_GTM_TM_LUMAFILTER2               (0x0558UL)
#define    DCAM_GTM_TM_RGB2YCOEFF0               (0x055CUL)
#define    DCAM_GTM_TM_RGB2YCOEFF1               (0x0560UL)
#define    DCAM_GTM_HW_YMIN                              (0x0564UL)
#define    DCAM_GTM_HW_YMAX                              (0x0568UL)
#define    DCAM_GTM_HW_YAVG                              (0x056CUL)
#define    DCAM_GTM_HW_TARGET_NORM            (0x0570UL)
#define    DCAM_GTM_HW_LR_INT                           (0x0574UL)
#define    DCAM_GTM_HW_LOG_MIN_INT              (0x0578UL)
#define    DCAM_GTM_HW_LOG_DIFF_INT              (0x057CUL)
#define    DCAM_GTM_HW_LOG_DIFF                      (0x0580UL)
#define    DCAM_GTM_SLICE_LINE_STARTPOS      (0x0584UL)
#define    DCAM_GTM_SLICE_LINE_ENDPOS          (0x0588UL)
#define    DCAM_GTM_STATUS                                 (0x0590UL)
#define    DCAM_GTM_HIST_XPTS_0                        (0x0600UL)
#define    DCAM_GTM_HIST_XPTS_2                        (0x0604UL)
#define    DCAM_GTM_HIST_XPTS_4                        (0x0608UL)
#define    DCAM_GTM_HIST_XPTS_6                        (0x060CUL)
#define    DCAM_GTM_HIST_XPTS_8                        (0x0610UL)
#define    DCAM_GTM_HIST_XPTS_10                      (0x0614UL)
#define    DCAM_GTM_HIST_XPTS_12                      (0x0618UL)
#define    DCAM_GTM_HIST_XPTS_14                      (0x061CUL)
#define    DCAM_GTM_HIST_XPTS_16                      (0x0620UL)
#define    DCAM_GTM_HIST_XPTS_18                      (0x0624UL)
#define    DCAM_GTM_HIST_XPTS_20                      (0x0628UL)
#define    DCAM_GTM_HIST_XPTS_22                      (0x062CUL)
#define    DCAM_GTM_HIST_XPTS_24                      (0x0630UL)
#define    DCAM_GTM_HIST_XPTS_26                      (0x0634UL)
#define    DCAM_GTM_HIST_XPTS_28                      (0x0638UL)
#define    DCAM_GTM_HIST_XPTS_30                      (0x063CUL)
#define    DCAM_GTM_HIST_XPTS_32                      (0x0640UL)
#define    DCAM_GTM_HIST_XPTS_34                      (0x0644UL)
#define    DCAM_GTM_HIST_XPTS_36                      (0x0648UL)
#define    DCAM_GTM_HIST_XPTS_38                      (0x064CUL)
#define    DCAM_GTM_HIST_XPTS_40                      (0x0650UL)
#define    DCAM_GTM_HIST_XPTS_42                      (0x0654UL)
#define    DCAM_GTM_HIST_XPTS_44                      (0x0658UL)
#define    DCAM_GTM_HIST_XPTS_46                      (0x065CUL)
#define    DCAM_GTM_HIST_XPTS_48                      (0x0660UL)
#define    DCAM_GTM_HIST_XPTS_50                      (0x0664UL)
#define    DCAM_GTM_HIST_XPTS_52                      (0x0668UL)
#define    DCAM_GTM_HIST_XPTS_54                      (0x066CUL)
#define    DCAM_GTM_HIST_XPTS_56                      (0x0670UL)
#define    DCAM_GTM_HIST_XPTS_58                      (0x0674UL)
#define    DCAM_GTM_HIST_XPTS_60                      (0x0678UL)
#define    DCAM_GTM_HIST_XPTS_62                      (0x067CUL)
#define    DCAM_GTM_HIST_XPTS_64                      (0x0680UL)
#define    DCAM_GTM_HIST_XPTS_66                      (0x0684UL)
#define    DCAM_GTM_HIST_XPTS_68                      (0x0688UL)
#define    DCAM_GTM_HIST_XPTS_70                      (0x068CUL)
#define    DCAM_GTM_HIST_XPTS_72                      (0x0690UL)
#define    DCAM_GTM_HIST_XPTS_74                      (0x0694UL)
#define    DCAM_GTM_HIST_XPTS_76                      (0x0698UL)
#define    DCAM_GTM_HIST_XPTS_78                      (0x069CUL)
#define    DCAM_GTM_HIST_XPTS_80                      (0x06A0UL)
#define    DCAM_GTM_HIST_XPTS_82                      (0x06A4UL)
#define    DCAM_GTM_HIST_XPTS_84                      (0x06A8UL)
#define    DCAM_GTM_HIST_XPTS_86                      (0x06ACUL)
#define    DCAM_GTM_HIST_XPTS_88                      (0x06B0UL)
#define    DCAM_GTM_HIST_XPTS_90                      (0x06B4UL)
#define    DCAM_GTM_HIST_XPTS_92                      (0x06B8UL)
#define    DCAM_GTM_HIST_XPTS_94                      (0x06BCUL)
#define    DCAM_GTM_HIST_XPTS_96                      (0x06C0UL)
#define    DCAM_GTM_HIST_XPTS_98                      (0x06C4UL)
#define    DCAM_GTM_HIST_XPTS_100                    (0x06C8UL)
#define    DCAM_GTM_HIST_XPTS_102                    (0x06CCUL)
#define    DCAM_GTM_HIST_XPTS_104                    (0x06D0UL)
#define    DCAM_GTM_HIST_XPTS_106                    (0x06D4UL)
#define    DCAM_GTM_HIST_XPTS_108                    (0x06D8UL)
#define    DCAM_GTM_HIST_XPTS_110                    (0x06DCUL)
#define    DCAM_GTM_HIST_XPTS_112                    (0x06E0UL)
#define    DCAM_GTM_HIST_XPTS_114                    (0x06E4UL)
#define    DCAM_GTM_HIST_XPTS_116                    (0x06E8UL)
#define    DCAM_GTM_HIST_XPTS_118                    (0x06ECUL)
#define    DCAM_GTM_HIST_XPTS_120                    (0x06F0UL)
#define    DCAM_GTM_HIST_XPTS_122                    (0x06F4UL)
#define    DCAM_GTM_HIST_XPTS_124                    (0x06F8UL)
#define    DCAM_GTM_HIST_XPTS_126                    (0x06FCUL)
#define    DCAM_LSC_WEI_TABLE                             (0x900UL)
#define    DCAM_LSC_WEI_LAST0                             (0x0D00UL)
#define    DCAM_LSC_WEI_LAST1                             (0x0D04UL)
#define    DCAM_RDS_COEF_TABLE                         (0x0D40UL)
#define    DCAM_PDAF_CORR_TABLE                      (0x0E00UL)
#define DCAM_AXIM_BASE                 s_dcam_aximbase
#define DCAM_AXIM_CTRL                 (0x0000UL)
#define DCAM_AXIM_DBG_STS              (0x0004UL)
#define DCAM_CAP_SENSOR_CTRL           (0x0008UL)

#define REG_DCAM_IMG_FETCH_START       (0x0020)
#define REG_DCAM_IMG_FETCH_CTRL        (0x0024)
#define REG_DCAM_IMG_FETCH_SIZE        (0x0028)
#define REG_DCAM_IMG_FETCH_X           (0x002c)
#define REG_DCAM_IMG_FETCH_RADDR       (0x0030)

#define DCAM_MMU_BASE                  s_dcam_mmubase
#define DCAM_MMU_EN                    (0x0000UL)
#define DCAM_MMU_UPDATA                (0x0004UL)
#define DCAM_MMU_MIN_VPN               (0x0008UL)
#define DCAM_MMU_VPN_RANGE             (0x000CUL)
#define DCAM_MMU_PT_ADDR               (0x0010UL)
#define DCAM_MMU_DEFAULT_PAGE          (0x0014UL)
#define DCAM_MMU_VAOR_ADDR_RD          (0x0018UL)
#define DCAM_MMU_VAOR_ADDR_WR          (0x001CUL)
#define DCAM_MMU_INV_ADDR_RD           (0x0020UL)
#define DCAM_MMU_INV_ADDR_WR           (0x0024UL)
#define DCAM_MMU_UNS_ADDR_RD           (0x0028UL)
#define DCAM_MMU_UNS_ADDR_WR           (0x002CUL)
#define DCAM_MMU_MISS_CNT              (0x0030UL)
#define DCAM_MMU_PT_UPDATA_QOS         (0x0034UL)
#define DCAM_MMU_VERSION               (0x0038UL)
#define DCAM_MMU_MIN_PPN1              (0x003CUL)
#define DCAM_MMU_PPN_RANGE1            (0x0040UL)
#define DCAM_MMU_MIN_PPN               (0x0044UL)
#define DCAM_MMU_PPN_RANGE2            (0x0048UL)
#define DCAM_MMU_VPN_PAOR_RD           (0x004CUL)
#define DCAM_MMU_VPN_PAOR_WR           (0x0050UL)
#define DCAM_MMU_PPN_PAOR_RD           (0x0054UL)
#define DCAM_MMU_PPN_PAOR_WR           (0x0058UL)
#define DCAM_MMU_REG_AU_MANAGE         (0x005CUL)
#define DCAM_MMU_STS                   (0x0080UL)
#define DCAM_MMU_EN_SHAD               (0x0084UL)

#define DCAM_CAP_SKIP_FRM_MAX          16
#define DCAM_FRM_DECI_FAC_MAX          4
#define DCAM_CAP_FRAME_WIDTH_MAX       4672
#define DCAM_CAP_FRAME_HEIGHT_MAX      3504

#define DCAM1_CAP_FRAME_WIDTH_MAX      3264
#define DCAM1_CAP_FRAME_HEIGHT_MAX     2448
#define DCAM2_CAP_FRAME_WIDTH_MAX      1632
#define DCAM2_CAP_FRAME_HEIGHT_MAX     1224

#define DCAM_CAP_X_DECI_FAC_MAX        4
#define DCAM_CAP_Y_DECI_FAC_MAX        4

#define DCAM_BIN_WIDTH_MAX            4672
#define DCAM_BIN_HEIGHT_MAX           3504

#define DCAM_SCALING_THRESHOLD         4672

#define CAMERA_SC_COEFF_UP_MAX         4
#define CAMERA_SC_COEFF_DOWN_MAX       4
#define CAMERA_PATH_DECI_FAC_MAX       4

#define DCAM_MAX_COUNT                 DCAM_ID_MAX
#define DCAM0_3DNR_ME_WIDTH_MAX        4608
#define DCAM0_3DNR_ME_HEIGHT_MAX       3456
#define DCAM1_3DNR_ME_WIDTH_MAX        (2128 << 1)
#define DCAM1_3DNR_ME_HEIGHT_MAX       (1600 << 1)

enum dcam_id {
	DCAM_ID_0 = 0,
	DCAM_ID_1,
	DCAM_ID_2,
	DCAM_ID_MAX,
};

enum camera_copy_id {
	CAP_COPY = BIT(0),
	RDS_COPY = BIT(1),
	FULL_COPY = BIT(2),
	BIN_COPY = BIT(3),
	AEM_COPY = BIT(4),
	PDAF_COPY = BIT(5),
	VCH2_COPY = BIT(6),
	VCH3_COPY = BIT(7),
	ALL_COPY = 0xFF,
};

#define DCAM_REG_WR(idx, reg, val) (REG_WR(DCAM_BASE(idx)+reg, val))
#define DCAM_REG_RD(idx, reg) (REG_RD(DCAM_BASE(idx)+reg))
#define DCAM_REG_MWR(idx, reg, msk, val) DCAM_REG_WR(idx, reg, \
	((val) & (msk)) | (DCAM_REG_RD(idx, reg) & (~(msk))))
#define DCAM_AXIM_WR(reg, val) (REG_WR(DCAM_AXIM_BASE+reg, val))
#define DCAM_AXIM_RD(reg) (REG_RD(DCAM_AXIM_BASE+reg))
#define DCAM_AXIM_MWR(reg, msk, val) DCAM_AXIM_WR(reg, \
	((val) & (msk)) | (DCAM_AXIM_RD(reg) & (~(msk))))

#define DCAM_MMU_WR(reg, val) (REG_WR(DCAM_MMU_BASE+reg, val))
#define DCAM_MMU_RD(reg) (REG_RD(DCAM_MMU_BASE+reg))

#endif /* _DCAM_REG_H_ */
